- name: Deploy Petite Expedition
  hosts: hosts
  tasks:
    - name: Create Petite User
      user:
        name: 'petite'
        password: '*'
      when: ansible_user_id == 'root'

    - name: Add keys to authorized users.
      ansible.posix.authorized_key:
        user: petite
        key: '{{ item }}'
      with_file:
        - pubkeys/danny.pub
        - pubkeys/jd.pub
        - pubkeys/desktop.pub
    - name: Add keys to authorized users.
      ansible.posix.authorized_key:
        user: root
        key: '{{ item }}'
      with_file:
        - pubkeys/danny.pub
        - pubkeys/jd.pub
        - pubkeys/desktop.pub

    - name: Create db directory if not already present
      file:
        path: /home/petite/petdb
        owner: petite
        state: directory

    - name: Copy frontend to remote
      ansible.posix.synchronize:
        src: ../frontend/
        dest: /usr/share/nginx/html/
        owner: false
      tags:
        - frontend

    - name: Copy the server binary
      copy:
        src: ../backend/target/debug/backend
        dest: /home/petite/backend
        mode: 0500
        owner: petite
    - name: Copy petite.service
      copy:
        src: petite.service
        dest: /etc/systemd/system/petite.service

    - name: Enable backend
      systemd_service:
        name: petite
        enabled: true
        state: restarted

    - name: Install required packages
      package:
        name:
          - nginx
        state: latest
    - name: Copy nginx config
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
    - name: Copy site config
      copy:
        src: petite.conf
        dest: /etc/nginx/default.d/petite.conf

    - name: Enable nginx
      systemd_service:
        name: nginx
        enabled: true
        state: reloaded
